name: Check JSON syntax

on:
  pull_request:

jobs:
  jsoncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
